[package]
name = "xsk-rs"
version = "0.9.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2024"
description = "Rust bindings for Linux AF_XDP sockets"
license = "MIT"
repository = "https://github.com/DouglasGray/xsk-rs"
readme = "README.md"
keywords = ["AF_XDP", "XSK", "eBPF", "XDP"]

[dependencies]
bitflags = "2.13.1"
cfg-if = "1.0.4"
libc = "0.2.189"
libxdp-sys = "0.2.4"
log = "0.4.33"

[patch.crates-io]
libxdp-sys = { git = "https://github.com/ninegamma/libxdp-sys.git", branch = "ninegamma" }

[dev-dependencies]
anyhow = "1.0.97"
crossbeam-channel = "0.5.15"
ctrlc = "3.4.6"
env_logger = "0.11.8"
etherparse = "0.21.0"
futures = "0.3.31"
rand = "0.10.2"
rtnetlink = "0.18.0"
serial_test = "4.0.1"
structopt = "0.3.26"

[dev-dependencies.tokio]
version = "1.44.2"
default-features = false
features = ["rt-multi-thread", "macros", "sync", "signal", "time"]
