name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install clang llvm gcc-multilib libelf-dev libpcap-dev build-essential
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check

  test:
    name: Test (${{ matrix.libxdp_build }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - libxdp_build: makefile
            cargo_args: ""
          - libxdp_build: cc
            cargo_args: "--features=use_cc_build"
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install clang llvm gcc-multilib libelf-dev libpcap-dev build-essential m4
      - uses: dtolnay/rust-toolchain@stable
      - run: ./run_all_tests.sh
        env:
          CARGO_ARGS: ${{ matrix.cargo_args }}
      - run: cargo test --doc ${{ matrix.cargo_args }}

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install clang llvm gcc-multilib libelf-dev libpcap-dev build-essential
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - run: cargo miri test --lib

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install clang llvm gcc-multilib libelf-dev libpcap-dev build-essential
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings
